name: Build and Release AppBundles (MATRIX)

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  find-scripts:
    name: Find and Prepare Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find build scripts
        id: find_scripts
        run: |
          if [ -d "${{ github.workspace }}/recipes" ]; then
            find "${{ github.workspace }}/recipes" -type f -name "*.sh" > scripts.txt
            echo "Found build scripts:"
            cat scripts.txt
          else
            echo "No recipes directory found."
            exit 1
          fi
      - name: Upload build scripts list
        uses: actions/upload-artifact@v3
        with:
          name: scripts-list
          path: scripts.txt

  build:
    name: Build and Run Scripts
    needs: find-scripts  # Ensure that the find-scripts job runs first
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64]
        include:
          - architecture: amd64
            out_suffix: '-amd64'
          - architecture: arm64
            out_suffix: ''
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download scripts list
        uses: actions/download-artifact@v3
        with:
          name: scripts-list
          path: ./scripts

      - name: Read and run each script
        run: |
          OUT_DIR="$HOME/out"
          mkdir -p "$OUT_DIR"

          DBIN_PGRS="dwarfs-tools bwrap-patched sharun yq jq"
          export GOBIN="$HOME/.local/bin"
          mkdir -p "$GOBIN"

          # Install required tools
          git clone --depth 1 --branch dev https://github.com/xplshn/pelf
          cp ./pelf/pelf* "$GOBIN"
          cp ./pelf/cmd/misc/* "$GOBIN"

          cd pelf/cmd/pelfd
          go build -o "$GOBIN/pelfd"
          cd ../dynexec/lib4bin
          go build -o "$GOBIN/lib4bin"

          wget -qO- "https://raw.githubusercontent.com/xplshn/dbin/master/stubdl" | sh -s -- --install "$GOBIN/dbin" add $DBIN_PGRS && \
          export PATH="$GOBIN:$PATH" && {
            ln -sfT "$GOBIN/dwarfs-tools" "$GOBIN/mkdwarfs"
            ln -sfT "$GOBIN/dwarfs-tools" "$GOBIN/dwarfs"
            ln -sfT "$GOBIN/bwrap-patched" "$GOBIN/bwrap"
          }

          ROOTFS_URL="$(curl -qsL https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/latest-releases.yaml | yq '.[0].file')"
          ROOTFS_URL="https://dl-cdn.alpinelinux.org/alpine/edge/releases/$(uname -m)/${ROOTFS_URL}"
          export ROOTFS_URL

          pelfCreator -m xplshn -n devEnv -p "fuse3 build-base go git" -z -c
          devEnv="$(echo ${{ github.workspace }}/devEnv*/AppRun)"

          # Iterate over the scripts and run them
          while IFS= read -r script; do
            if [ -f "$script" ]; then
              echo "Running $script..."
              chmod +x "$script"
              "${devEnv}" "$script"
            else
              echo "Script $script not found, skipping."
            fi
          done < ./scripts/scripts.txt

      - name: Upload Artifacts
        run: |
          ls "$HOME/out"
          echo "OUT_DIR=${OUT_DIR}" >> $GITHUB_ENV

  manage-tags:
    name: Manage Tags
    runs-on: ubuntu-latest
    needs: build  # Ensure it runs after all builds are done

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Manage Tags
        run: |
          git fetch --tags
          TAGS=$(git tag | sort -V)
          TAG_COUNT=$(echo "$TAGS" | wc -l)

          if [ "$TAG_COUNT" -gt 5 ]; then
            TAGS_TO_DELETE=$(echo "$TAGS" | head -n -1)

            for TAG in $TAGS_TO_DELETE; do
              echo "Deleting tag: $TAG"
              git tag -d "$TAG" || echo "Tag $TAG could not be deleted locally."
              git push origin --delete "$TAG" || echo "Tag $TAG could not be deleted from remote."
            done
          else
            echo "Tag count is $TAG_COUNT, no tags to delete."
          fi

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Weekly Release - Run ${{ github.run_id }}"
          automatic_release_tag: weekly-release-${{ github.run_id }}
          prerelease: false
          draft: false
          files: |
            ${{ env.OUT_DIR }}/*.AppBundle${{ matrix.out_suffix }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
